"""initial schema

Revision ID: 64365c12b40f
Revises: 
Create Date: 2026-08-03 11:02:28.892166
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '64365c12b40f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # evidence.embedding is a pgvector column, so the extension must exist before
    # any table referencing it is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('handle', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('ig_user_id', sa.String(length=64), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=True),
    sa.Column('is_professional', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('reels_analysed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'handle')
    )
    op.create_index(op.f('ix_creators_handle'), 'creators', ['handle'], unique=False)
    op.create_table('doc_cache',
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=256), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('url_hash')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_prompt_hash'), 'llm_calls', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_llm_calls_report_id'), 'llm_calls', ['report_id'], unique=False)
    op.create_table('mentions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ig_comment_id', sa.String(length=64), nullable=True),
    sa.Column('ig_media_id', sa.String(length=64), nullable=True),
    sa.Column('requester', sa.String(length=128), nullable=True),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ig_comment_id')
    )
    op.create_index(op.f('ix_mentions_ig_media_id'), 'mentions', ['ig_media_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('shortcode', sa.String(length=64), nullable=False),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=True),
    sa.Column('ingest_path', sa.String(length=16), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('phashes', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'shortcode')
    )
    op.create_index(op.f('ix_media_shortcode'), 'media', ['shortcode'], unique=False)
    op.create_index(op.f('ix_media_url_hash'), 'media', ['url_hash'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('validity_score', sa.Float(), nullable=True),
    sa.Column('validity_ci_low', sa.Float(), nullable=True),
    sa.Column('validity_ci_high', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('lean_economic', sa.Float(), nullable=True),
    sa.Column('lean_social', sa.Float(), nullable=True),
    sa.Column('lean_confidence', sa.Float(), nullable=True),
    sa.Column('lean_applicable', sa.Boolean(), nullable=False),
    sa.Column('lean_rationale', sa.Text(), nullable=True),
    sa.Column('forensics_score', sa.Float(), nullable=True),
    sa.Column('forensics_confidence', sa.Float(), nullable=True),
    sa.Column('subscores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('video_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_media_id'), 'reports', ['media_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=32), nullable=False),
    sa.Column('checkworthiness', sa.Float(), nullable=False),
    sa.Column('t_start', sa.Float(), nullable=True),
    sa.Column('t_end', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('verbatim', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('verdict', sa.String(length=24), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_report_id'), 'claims', ['report_id'], unique=False)
    op.create_index(op.f('ix_claims_verdict'), 'claims', ['verdict'], unique=False)
    op.create_table('forensics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('signal', sa.String(length=64), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('calibrated_prob', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forensics_report_id'), 'forensics', ['report_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=256), nullable=True),
    sa.Column('publisher_credibility', sa.Float(), nullable=True),
    sa.Column('publisher_lean', sa.Float(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('stance', sa.String(length=16), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=True),
    sa.Column('cited', sa.Boolean(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_claim_id'), 'evidence', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_claim_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_forensics_report_id'), table_name='forensics')
    op.drop_table('forensics')
    op.drop_index(op.f('ix_claims_verdict'), table_name='claims')
    op.drop_index(op.f('ix_claims_report_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_media_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_media_url_hash'), table_name='media')
    op.drop_index(op.f('ix_media_shortcode'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_mentions_ig_media_id'), table_name='mentions')
    op.drop_table('mentions')
    op.drop_index(op.f('ix_llm_calls_report_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_prompt_hash'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_table('doc_cache')
    op.drop_index(op.f('ix_creators_handle'), table_name='creators')
    op.drop_table('creators')
    # ### end Alembic commands ###
